FROM nginx:alpine

# Copy Nginx Config to replace default server block
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy Flutter Web Build
COPY build/web /usr/share/nginx/html

# Copy Android APK
COPY build/app/outputs/flutter-apk/app-release.apk /usr/share/nginx/html/app-release.apk

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
